nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - '80:80'
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

server:
  image: toubi/ocsigen
  working_dir: /mnt/src
  hostname: genehub
  ports:
    - '8080:8080'
  volumes:
    - .:/mnt
  command: make test.opt
  environment:
    VIRTUAL_HOST: 'genehub.dev'
